# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build Base image
      inputs:
        command: build
        arguments: -t base_cloudshell 
        buildContext: $(Build.SourcesDirectory)
        dockerfile: '$(Build.SourcesDirectory)/linux/base.Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build Tools image
      inputs:
        command: build
        arguments: -t tools_cloudshell --build-arg IMAGE_LOCATION=base_cloudshell 
        buildContext: $(Build.SourcesDirectory)
        dockerfile: '$(Build.SourcesDirectory)/linux/tools.Dockerfile'
        tags: |
          $(tag)
